### ISSUE TITLE
Newer versions of Unity do not properly build using gameci and unity-orb

### ISSUE THREAD

**Issue by rhulzingsrio** [game-ci/unity-orb#58]
**Orb version**

1.6.0

**Execution environment**

- Executor: unity/ubuntu
- Target platform: android
- Unity Editor version: 2021.3.30f1

**Bug description**

Cannot build in gameci using more recent unity versions, it errors out, saying it cannot find the manifest for unityci/editor:ubuntu-2021.3.30.f1-android-1 which does not exist on docker. unityci/editor:ubuntu-2021.3.30.f1-android-2 does exist, but I cannot find a way to change it to point to the correct docker image. 

The file src/executors/ubuntu.yml looks like there's a hardcoded 1 in the docker image.

**How to reproduce**

- Create a unity project using version 2021.3.30f1 and hook it up to circleci. Build the project using the unity orb. The build will immediately fail.

**Expected behavior**

The build should download the correct unity version from docker so it can continue building.

**Additional details**

![image](https://github.com/game-ci/unity-orb/assets/141655503/aa86794f-0698-4b9d-81a2-614b0cbb6b0e)

**Comment by alan-smarter-reality** [comment]
This is very much affecting our ability to use GameCI with CircelCI. There are no new docker images with -1 for the LTS 2022 version above ubuntu-2022.3.7f1-android-1. There are 2023 versions, but that is not LTS, which we require.
